version: "3.9"

services:
  api:
    container_name: finance-api
    image: weehong/finance-api:latest
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Singapore
      db-url: jdbc:postgresql://db:5432/${DB_NAME}
      db-user: ${DB_USER}
      db-pass: ${DB_PASS}
      oauth2-issuer: ${AUTH0_ISSUER}
      oauth2-audience: ${AUTH0_AUDIENCE}
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: finance-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: