spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2-issuer:https://finance-app-development.jp.auth0.com/}
  datasource:
    url: ${db-url:jdbc:postgresql://localhost:5432/finance-db}
    username: ${db-user:ayden}
    password: ${db-pass:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
installment:
  cron: "*/10 * * * * *"
auth0:
  audience: ${oauth2-audience:finance-api-development}