name: Build & Deploy Spring Boot Application


on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot for Finance API
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Unit Tests
        run: ./gradlew test --tests "*"
        env:
          TZ: Asia/Singapore

      - name: Build the Application
        run: ./gradlew clean build
        env:
          TZ: Asia/Singapore

      - name: Build the Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_USERNAME}}/finance-api:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/finance-api:latest